### ISSUE TITLE
Read user settings before toggling.

### ISSUE THREAD

**Issue by ahmedkhalf** [kdav5758/TrueZen.nvim#10]
Hello, I already commented on another issue, but I am opening an issue for visibility:

Why can't TrueZen.nvim just read my settings before toggling and store them. I want to have some peace of mind, because now if I want to hide sign columns in my neovim config i'l have to change it in two places... :(

[Comment LInk](https://github.com/kdav5758/TrueZen.nvim/issues/4#issuecomment-824262495)

**Comment by kdav5758** [comment]
Your are right. It's unfair for users to have to change their own settings just for a plug-in to work. And although the different prefixes were created for users to change stuff according to each event (hiding & showing) and it seems that everyone one likes this system, I'll tackle it.

Since restoring user's config simply defeats the purpose of having the *after_shown* type of event, what I could do is to provide users with both options. In this way users like you can enable a `restore_user_settings_after_untoggle = true` option to completely ignore the *after_shown* settings. And the others that'd like to let the plug-in manage all this events/settings for them could set it to `false`.

Does this sounds good to you? :)

If yes then I'll try to implement it as soon as possible!

**Comment by ahmedkhalf** [comment]
Sounds Great!

**Comment by kdav5758** [comment]
Hey Sorry for taking too long. I didn't quite know what was the best way to implement this, so yeah excuse the delay! Go to this [new README section](https://github.com/kdav5758/TrueZen.nvim#minimalist) to learn how to configure it.

Enjoy! :+1:

**Comment by ahmedkhalf** [comment]
Thank you

**Comment by ahmedkhalf** [comment]
@kdav5758 It doesn't work, I updated the plugin and set this as my config:
```
lua <<EOF
-- setup for TrueZen.nvim
require("true-zen").setup({
  true_false_commands = false,
  cursor_by_mode = false,
  bottom = {
    en_laststatus = 0,
    hidden_ruler = false,
    hidden_showmode = false,
    hidden_showcmd = false,
    hidden_cmdheight = 1,
  },
  top = {
    hidden_showtabline = 0,
  },
  left = {
    hidden_number = false,
    hidden_relativenumber = false,
    hidden_signcolumn = "no",
  },
  ataraxis = {
    left_right_padding = 40,
  },
  minimallist = {
    store_and_restore_settings = true,
    show_vals_to_read = {
      "shown_showtabline",
      "shown_laststatus,",
      "shown_ruler",
      "shown_showmode",
      "shown_showcmd",
      "shown_cmdheight",
      "shown_number",
      "shown_relativenumber",
      "shown_signcolumn",
    },
  }
})

EOF
```

**Comment by kdav5758** [comment]
Hahaha, don't worry, it's working! is just that you added:

```lua
    show_vals_to_read = {
      "shown_showtabline",
      "shown_laststatus,",
      "shown_ruler",
      "shown_showmode",
      "shown_showcmd",
      "shown_cmdheight",
      "shown_number",
      "shown_relativenumber",
      "shown_signcolumn",
    },
```

To the `show_vals_to_read` table! and the values of this table are *ignore* from the restore_and_save thing. This means that if you add `"shown_signcolumn"` to the table it will *read* the value from TrueZen's config an *ignore* it from the user's settings (which means that it won't save it nor restore it when exiting)

Here is a video proving that it works:

https://user-images.githubusercontent.com/58336662/117354073-8c690980-ae76-11eb-9827-1138c42aa60c.mp4

As you can see I don't have `"shown_signcolumn"` in that table because **I want it** to be stored and **not to be read** from TrueZen's config

Please excuse me, I actually forgot to mention what this table is for in the README! I'll update it as soon as possible.

**Comment by kdav5758** [comment]
Okay, just updated the README. Hope it's clear now!

**Comment by ahmedkhalf** [comment]
It's not working... Even with a minimal config and most recent plugin version.
```
-- setup for TrueZen.nvim
require("true-zen").setup({
  minimallist = {
    store_and_restore_settings = true,
    show_vals_to_read = {},
  },
})
```

https://user-images.githubusercontent.com/36672196/117360386-c7e0f380-aec9-11eb-8fbe-84043b51d604.mp4

As you can see even my cmd height isnt getting set properly.

**Comment by ahmedkhalf** [comment]
Also I'm getting this weird error after untoggling TZAttarix:
```
E5108: Error executing lua ...Zen.nvim/lua/true-zen/services/mode-ataraxis/service.lua:3
82: Vim(setlocal):E540: Unclosed expression sequence: statusline=%#GalaxyBufferType#%{lu
aeval('require(                                                                         
Press ENTER or type command to continue   
```

**Comment by kdav5758** [comment]
> It's not working... Even with a minimal config and most recent plugin version.

Because of the way I coded the restoring part thing of the program, you should ***at least*** have all the settings (no matter their value, just put something in there with the corresponding data type) with the `shown_` prefix so that TrueZen can match them with your current config's values instead of the ones that are set on TrueZen's config. I didn't expect people to stay only with the "minimum" config as you did in here, since it's kind of essential, but anyways I will specify that as well in the README.

You could either grab the example config for `init.vim` users in the README or just copy and paste mine that I'm gonna leave below since it seems you and I have a similar setup:

```lua
-- note: `true-zen` would resolve to true-zen.init
local true_zen = require("true-zen")

-- setup for TrueZen.nvim
true_zen.setup({

    true_false_commands = false,
	cursor_by_mode = false,
	bottom = {
		hidden_laststatus = 0,
		hidden_ruler = false,
		hidden_showmode = false,
		hidden_showcmd = false,
		hidden_cmdheight = 1,

		shown_laststatus = 2,
		shown_ruler = true,
		shown_showmode = false,
		shown_showcmd = false,
		shown_cmdheight = 1
	},
	top = {
		hidden_showtabline = 0,

		shown_showtabline = 2
	},
	left = {
		hidden_number = false,
		hidden_relativenumber = false,
		hidden_signcolumn = "no",

		shown_number = true,
		shown_relativenumber = false,
		shown_signcolumn = "no"
	},
	ataraxis = {
		ideal_writing_area_width = 0,
		just_do_it_for_me = true,
		left_padding = 10,
		right_padding = 30,
		top_padding = 2,
		bottom_padding = 2,
		custome_bg = "",
		disable_bg_configuration = false,
		force_when_plus_one_window = true,
		force_hide_statusline = true
	},
	focus = {
		margin_of_error = 5,
		focus_method = "experimental"
	},
	minimalist = {
		store_and_restore_settings = true,
		show_vals_to_read = {
			"shown_showtabline"
		}
	},
	events = {
		before_minimalist_mode_shown = false,
		before_minimalist_mode_hidden = false,
		after_minimalist_mode_shown = false,
		after_minimalist_mode_hidden = false
	},
	integrations = {
		integration_galaxyline = true,
		integration_vim_airline = false,
		integration_vim_powerline = false,
		integration_tmux = false,
		integration_express_line = false,
		integration_gitgutter = false,
		integration_vim_signify = false,
		integration_limelight = false,
		integration_tzfocus_tzataraxis = false,
		integration_gitsigns = true
	}
})
```



> As you can see even my cmd height isnt getting set properly.

If what I just told you to do above didn't solve it then it's an issue with your env/setup. Consider upgrading to latest nightly (if I'm not wrong nightly received some commints today like 6 hours ago, so yeah grab the app image)


Sid note:
* I know it's tedious but please read the README, most of the stuff I just said can be found there and is explained in a better manner. :+1: 
* The ""Beta testers""" of the plugin and I didn't find any issues whatsoever with the most recent updates.
