### ISSUE TITLE
gitsigns.nvim integration

### ISSUE THREAD

**Issue by ahmedkhalf** [kdav5758/TrueZen.nvim#11]
Hello, I would like gitsigns integration.

Plugin link: https://github.com/lewis6991/gitsigns.nvim

**Comment by kdav5758** [comment]
Good integration idea! I'll be working on it soon...

**Comment by ahmedkhalf** [comment]
I think this one, https://github.com/lewis6991/gitsigns.nvim/blob/4c494ba4535aec533af9a5694c716e4e1e3995c4/lua/gitsigns.lua#L885.

**Comment by kdav5758** [comment]
@ahmedkhalf after reading Gitsigns' source code and asking some people about it... I found out that there is no way to determine whether it's toggled or not. I already [opened an issue](https://github.com/lewis6991/gitsigns.nvim/issues/167) in the plugin's repo for the creator to expose the var(s) that control this so that people like can develop integrations with his plugin.

For now we'll have to wait for the author to reply and approve of this.

**Comment by ahmedkhalf** [comment]
Perfect! Tnx for your efforts. And amazing plugin btw.

**Comment by kdav5758** [comment]
Hello again! Sorry for taking too long. Gitsigns' author just released an unstable version of the plugin's API, however, I was able to make it work with that.

The integration passed all the tests and the doc for it was introduced too. You may now enjoy it by enabling it on the `integration = {}` table like so:
```lua
integration_gitsigns = true
```
