### ISSUE TITLE
:TZAtaraxis results in E5108: BG Color unknown 

### ISSUE THREAD

**Issue by shaunsingh** [kdav5758/TrueZen.nvim#12]
Running :TZAtaraxis rusults in the following output 
<img width="1047" alt="Screen Shot 2021-04-26 at 5 23 51 PM" src="https://user-images.githubusercontent.com/71196912/116152686-38129c80-a6b4-11eb-8dc9-40ca1b797876.png">

The screen looks somewhat fine except for two lines of ~~~ 

<img width="1440" alt="Screen Shot 2021-04-26 at 5 24 20 PM" src="https://user-images.githubusercontent.com/71196912/116152744-4791e580-a6b4-11eb-97ef-350e5ed174d4.png">

Not sure what could be the issue. Using Latest Neovim and all plugins are updated. :TZMinimalist works fine

**Comment by shaunsingh** [comment]
edit: unkown_bg_color_fix = true worked for me, sorry for wasting your time

**Comment by kdav5758** [comment]
Hey! I'm sorry but I never got to see this issue because you closed it pretty much instantly. I actually removed the `unkown_bg_color_fix` setting for a better one, which is `custome_bg = "<hex_code/solid_color>"` so that users could specify a temporal BG color for TrueZen to use.

I think you should now use this setting instead of the `unkown_bg_color_fix` for this purposes. However, I did realized that not many people will like to have BG (which is nonsensical but whatever), so I introduced the setting again with a new name and all. This is what the settings for Ataraxis look like now:

```lua
	ataraxis = {
		just_do_it_for_me = true,
		left_padding = 40,
		right_padding = 40,
		top_padding = 1,
		bottom_padding = 1,
		custome_bg = "",
		disable_bg_configuration = false
	},
```

As you can see the option was re-branded to `disable_bg_configuration`, so in case you still want that, then you may use it (although I strongly recommend only using it if you don't like setting a BG color, even if it's temporal and only for Ataraxis) :+1:

**Comment by shaunsingh** [comment]
Thanks for your help, I love your work on this Plugin!
