### ISSUE TITLE
Tmux integration in minimalist_mode.

### ISSUE THREAD

**Issue by uttarayan21** [kdav5758/TrueZen.nvim#13]
It'd be great to have tmux integration in minimalist mode similar to ataraxis mode.

Also maybe a toggle to switch from transparent to solid background.

I'm using something like this as of now.
```vim
let t:transparent = 1
function! ZenToggle()
    if t:transparent == 0
        hi Normal guibg=NONE ctermbg=NONE
        hi NonText guibg=NONE ctermbg=NONE
        TZMinimalistT
        silent! !tmux set -g status on
        let t:transparent = 1
    else 
        hi Normal ctermfg=255 ctermbg=234 cterm=NONE guifg=#EEEEEE guibg=#1C1C1C gui=NONE
        hi NonText ctermfg=234 ctermbg=234 cterm=NONE guifg=#1C1C1C guibg=#1C1C1C gui=NONE
        TZMinimalistF
        silent! !tmux set -g status off
        let t:transparent = 0
    endif
endfunction
```

**Comment by kdav5758** [comment]
Hey! I'm sorry but the idea of having Minimalist mode is to be able to hide NeoVim's UI components [from the top, left and bottom], while Ataraxis is for literally deactivating everything, and thus the integrations.

For your specific use case I'd recommend you checking out the **Events** section on the README; as you'll see, the **Events** only apply for Minimalist mode, however since Ataraxis is simply a super extension of Minimalist mode but with a *cape*, it also applies for it.

Try this:

```lua
local true_zen = require("true-zen")

-- this will hide it
true_zen.after_minimalist_mode_hidden = function ()
	require("true-zen.services.bottom.integrations.integration_tmux").disable_element()
end

-- optional if you want to enable it again when untoggled
true_zen.after_minimalist_mode_shown = function ()
	require("true-zen.services.bottom.integrations.integration_tmux").enable_element()
end
```

Remember that if you want to use these events, you must enble their corresponding settings. So in this case:

```lua
after_minimalist_mode_shown = true,
after_minimalist_mode_hidden = true
```

---

As for your second issue... My goal with this plugin was to interfere at least as possible with the user's color-scheme, unlike Goyo.vim that did exactly that and caused many conflicts. Because of this, I think this is a little bit out of the scope of the plugin too, for this instead of using a vim func, consider using auto-commands to make it shorter, or, as above, use the built-in **Events**:

```lua
local true_zen = require("true-zen")

true_zen.after_minimalist_mode_hidden = function ()
	vim.api.nvim_exec([[
                hi Normal guibg=NONE ctermbg=NONE
                hi NonText guibg=NONE ctermbg=NONE
	]], false)
end

true_zen.after_minimalist_mode_shown = function ()
	vim.api.nvim_exec([[
                hi Normal ctermfg=255 ctermbg=234 cterm=NONE guifg=#EEEEEE guibg=#1C1C1C gui=NONE
                hi NonText ctermfg=234 ctermbg=234 cterm=NONE guifg=#1C1C1C guibg=#1C1C1C gui=NONE
	]], false)
end
```

Simply use the two together to get a more *native* solution.


Side Notes:
* In order of execution: integrations are executed between the *before* and the *after* events. So if you have the Tmux integration enabled but also an *Event* that enables it *after_minimalist_hides_everything*, in the end Tmux will be enabled.
* the **Events** settings will be moved to their own table in the future, so beware of that :+1:
