### ISSUE TITLE
airblade/vim-gitgutter not showing when in TZAtaraxis mode

### ISSUE THREAD

**Issue by keithlo** [kdav5758/TrueZen.nvim#14]
I have ```	integrations = {
		integration_gitgutter = false,
	}```
but am not seeing the git gutter while in Ataraxis mode

**Comment by kdav5758** [comment]
Hey! I'm sorry if the README was a little bit unclear but the `booleans` in this case indicate if the extension is enabled of not, so:

**false** = **disabled**
**true** = **enabled**

Disabling an extension ≠ doing the exact opposite as if fit was enabled, it simply deactivates the integration. So, in your case, what you are doing by setting `integrations = { integration_gitgutter = false, }` is simply telling TrueZen.nvim to disable the Gitgutter integration, `not to toggle it when you enter Ataraxis mode`. Due to the fact that every single extension does something different and has different verbs describing what they do/current state, it's simply better to have booleans for the settings.

In the case you'd want to show Gitgutter when the integration is disabled, consider using the native **Events** that TrueZen provides (or you may also use vim auto-commands, whichever you'd like). Just keep in mind that the **Events** apply for Minimalist mode, but since Ataraxis mode is kind of a super extension on Minimalist, it'll work on it too. This is what it'd look like in your case:

```lua =
local true_zen = require("true-zen")

true_zen.after_minimalist_mode_hidden = function ()

        -- native way TrueZen provides
        require("true-zen.services.bottom.integrations.integration_gitgutter").enable_element()

        -- using normal commands
        -- vim.cmd("silent! GitGutterEnable")
end

```


Don't forget that if you want this event to be executed, you should enable it in the settings, so in your case:
```lua
after_minimalist_mode_hidden = true
```


Actually, after re-reading the README I think I should have been a little bit more specific. I'll update that ASAP. And also, I'll document the integration's functions so that anybody that'd want to use TrueZen.nvim's integrations can modify their behavior.

Cheers!
