### ISSUE TITLE
Set desired width instead of padding

### ISSUE THREAD

**Issue by evantravers** [kdav5758/TrueZen.nvim#16]
Great job on this plugin, I'm enjoying it so far!

I think that the _killer_ feature would be to be able to set a desired width rather than set the padding on left and right individually… to be able to restrict the "final" column to some width would be 👌.

I'll try hacking around to see if I can make a prototype, but I figured I'd let you know too.

**Comment by kdav5758** [comment]
Hey! I'm not entirely sure by what you meant by "Set desired width instead of padding". Based on the description you gave I'll assume what you want is to be able to have a width number that applies for both the left and the right padding.

I personally don't know why you can't just *change the number on two places*, but if that's what you want, this is how you can accomplish this:

```lua
width = 20

local foo = {

  bar = width
  baz = width
}

io.write(tostring(foo["bar"]).."\n")
-- output: 20
-- same output if you get the other one
```

Pass a global var to the settings' values of the settings that you want them to have the same value (don't forget about the data types each setting must receive).

If this is what you wanted, then please consider closing the issue.

Also thanks for the compliment. Good to know somebody found it useful :)

Cheers!

**Comment by evantravers** [comment]
@kdav5758… thanks for the response! Let me explain my use case:

I like to write my prose using a good reading width… [line-length should be 45-90 characters](https://practicaltypography.com/typography-in-ten-minutes.html) for maximum readability.

Sometimes I'm writing on different monitors, with different zoom levels… or in a split… so I _could_ find a left width and right width that work for my laptop monitor at 100% but as soon as I split the window or use a different monitor, I won't have my desired reading width.

I'd like to have a variant of `just_do_it_for_me` that lets me choose the width of the "writing" column, and automatically set the side widths based on the current window width.

![image](https://user-images.githubusercontent.com/62209/116712091-1c9be000-a999-11eb-9e7e-1b1ec53a04da.png)

**Comment by kdav5758** [comment]
Ooh so what you want is the have a `just_do_it_for_me` variant that applies to specific UI elements and for the rest, take a default value (e.g the writing column, aka Left UI)? This is what I could do:

```lua
	ataraxis = {
		just_do_it_for_me = {
			left = false,
			righ = true,
			top = true,
			bottom = true
		},
		left_padding = 40,
		right_padding = 40,
		top_padding = 1,
		bottom_padding = 1,
        }

```

In this case `just_do_it_for_me` will set the widths of the UI elements that you set to `true`, and for the ones you set to `false` it'll just take the value from the settings.

Let me know if this works for ya!

Oh and also, vim works with "cells", not with pixels, inches or chars.

**Comment by evantravers** [comment]
I just want to set the prose area width, and it be centered and readable. Cells or chars, I can work with either.

**Comment by kdav5758** [comment]
Hello again! first of all, excuse me for taking too long. Second of all, your feature is ready!!
This is how it looks:

![new_feature](https://user-images.githubusercontent.com/58336662/116790808-f0a55b00-aa7b-11eb-9af6-20766a25b68b.gif)

As you can see, the first time I toggled `TZAtaraxis` I had the `just_do_it_for_me` setting set to true (because it's what I personally prefer). However, the second time I toggled it I had the `ideal_writing_area_width` setting set to `20` (as an example, of course). It worked perfectly and my ideal width was kept!

Needless to say, enabling the `ideal_writing_area_width` setting (putting a number greater than `0`) make TrueZen.nvim ignore `just_do_it_for_me`, `left_padding`, and `right_padding` for obvious reasons.

Right now, the feature is on the `dev` branch, but I'll merge it to main as soon as the doc is ready, and of course, close this issue afterwards...

**Comment by kdav5758** [comment]
The feature was merged and the doc was updated.

Enjoy!
