### ISSUE TITLE
Commands on enter and leave

### ISSUE THREAD

**Issue by AckslD** [kdav5758/TrueZen.nvim#2]
In Goyo I made use of the events `GoyoEnter` and `GoyoLeave` to trigger some additional things. Does TrueZen have something similar? This does not have to be events but could also be functions that could be passed to setup.

**Comment by akinsho** [comment]
This would be useful so I could hook into `tmux` and disable my tmux statusline etc.

**Comment by kdav5758** [comment]
Hey! Thanks for opening this issue. Due to the "boom" this plug-in had there are already several features in the "production line".

This'd be a really useful feature to have and I'll get to it... Eventually. Unfortunately, the last time I used Goyo.vim was a few months ago, so I really don't remember much about how this specific feature worked.

Please correct me if I'm wrong but with this you could execute vim commands before and after it was toggled right?

If this is the case, then I'll work on it as soon as possible.

**Comment by akinsho** [comment]
@kdav5758 totally understandable re. multiple issues. Thanks for this plugin 🙏🏿. 

Regarding how to implement, this should/could actually be quite easy to implement depending on how you chose to tackle it.
e.g.
```lua
-- some logic executing before TZMinimalist
vim.cmd('doautocmd User TZMinimalistPre')
enable_tzminimalist()

-- later on when TZMinimalist is closed
disable_tzminimalizt()
vim.cmd('doautocmd User TZMinimalistPost')

--- Method 2t
require('true-zen').setup {
  on_enter = function()
   -- user fills this out
  end,
  on_exit = function()
   -- user fills this out
  end,
}

user_config.on_enter()
enable_tzminimalist()

-- later on when TZMinimalist is closed
disable_tzminimalizt()
user_config.on_exit()
```
The value of method one is that a user can just listed for user autocommands in their config and execute their own logic. This is how `goyo` did it. Method 2 depends on how the user config is stored and how easily it can be accessed but the value for the user is that they can just specify this behaviour in their setup config rather than creating new autocommands 🤷🏿

**Comment by kdav5758** [comment]
@akinsho

That's going to be a separate feature, but now that you mentioned that, I'll try to release this "GoyoEnter.." like feature first.

Thanks!

**Comment by AckslD** [comment]
To me method 2 seems cleaner :) Although that's maybe mostly cause autocommands are not yet exposed in the lua api.

**Comment by kdav5758** [comment]
@AckslD I agree with you 100%. I also think it's cleaner this way, so I'm gonna do it like this.
Again, thanks @akinsho for proposing those two amazing solutions!

**Comment by kdav5758** [comment]
Done.

https://user-images.githubusercontent.com/58336662/115469823-f177fa80-a1fa-11eb-9833-8ac7d44cbd2b.mp4

I went one step ahead and added some settings so that users that don't need it can save that execution time + you can configure what happens before and after minimalist mode hides everything and the same for when it shows everything. Also, this works with the Ataraxis mode since Ataraxis is basically a super extension of Minimalist mode that adds padding to the text. Just keep in mind that in order of execution, Ataraxis calls Minimalist after adding the paddings.

Currently the feature is on the `dev-mode-minimalist` branch, so please don't use until it's merged with main. I'll probably be committing some stuff there + there are no docs explaining how to set that up yet. So yeah, it's better to wait for the release.

**Comment by akinsho** [comment]
@kdav5758 that looks great 👍🏿 maybe leave this issue open though until it's merged in to the main branch so people can test it out and report back here 🤷🏿‍♂️ (obvs your project so up to you 😄 )

**Comment by kdav5758** [comment]
Thanks @akinsho for the suggestion. I told a friend of mine to test it and it failed. It's now fixed and without your message I would have merged it to main thinking it worked.

I will close this issue only after it's merged to main. If you want, you can test the feature right now from the `dev-mode-minimalist` branch (`"use {"kdav5758/TrueZen.nvim", branch = "dev-mode-minimalist"}"`). There are no docs explaining how to use them yet but I guess that just by showing you this:

```lua
local true_zen = require("true-zen")
true_zen.setup({
	before_minimalist_mode_shown = true,
	before_minimalist_mode_hidden = true,
	after_minimalist_mode_shown = true,
	after_minimalist_mode_hidden = true,
.....
}

true_zen.after_minimalist_mode_hidden = function ()
	vim.cmd("echo 'I ran after minimalist mode hid everything :)'")
end

true_zen.before_minimalist_mode_hidden = function ()
	vim.cmd("echo 'I ran before minimalist mode hid everything :)'")
end

true_zen.after_minimalist_mode_shown = function ()
	vim.cmd("echo 'I ran after minimalist mode showed everything :)'")
end

true_zen.before_minimalist_mode_shown = function ()
	vim.cmd("echo 'I ran before minimalist mode showed everything :)'")
end
```

you'll know how to use it ;)

Note: this feature is ready and should be working from now on, it just hasn't be merged with `main`

**Comment by akinsho** [comment]
@kdav5758 do I need to specify the booleans for the functions to work? could potentially just check their existence before calling them instead?, so you dont get issues like my handler isn't working why?? 😭 , oh I forgot to set a boolean 😆

**Comment by kdav5758** [comment]
@akinsho
> oh I forgot to set a boolean laughing

Good to know it's working for you!
Btw, unrelated to this issue but related to your first comment: as you can see in [this commit](https://github.com/kdav5758/TrueZen.nvim/commit/eaddac1d5f1ad6414a5a5298ddd6d16b14df8c6c) the tmux integration is ready for use and supports verification (check whether tmux is running or not instead of just turning it on and off). But as always, don't use it because I'll be commiting some stuff for the other integrations to that branch :)

You can check out the to-do of this project here: https://trello.com/b/nGGv2jk7
(this Trello board will also be added to the README)

**Comment by kdav5758** [comment]
All the new features were merged, including the ones discussed in this issue. Since it's being +10hrs without any issue I'll assume everything is working as expected.
