### ISSUE TITLE
How to enable git-gutter (left side marks, near the line numbers)?

### ISSUE THREAD

**Issue by qazip** [kdav5758/TrueZen.nvim#25]
I want to enable git-gutter (left side marks, near the line numbers) when using minimalist mode. Here is what I have in my init.vim file:

```
"Truezen
autocmd VimEnter * TZMinimalist
autocmd VimEnter * TZTop
autocmd VimEnter * TZLeft

lua << EOF
local true_zen = require("true-zen")
true_zen.setup({
  minimalist = {
    store_and_restore_settings = false,
    show_vals_to_read = {}
  },
  integrations = {
    integration_gitgutter = true,
  }
})
EOF
```

Everything works, other than the git integration. Any suggestions?

**Comment by kdav5758** [comment]
Okay so first of all, excuse me for not mentioning this in the README, but integrations only work for Ataraxis mode (I'll go correct that now) because Minimalist mode is only for deactivating UI components. Second of all, If you enable TZMinimalist to run at startup then there is no reason to `TZTop` and `TZLeft`, because Minimalist mode already runs them in its body.

Also, I really don't use GitGutter and don't know what the "left side marks" are, but if those marks depend on you having the numberline, then enable the numberline when entering Minimalist mode using the Left UI table's settings.

Furthermore, remember that in order of execution: here you are first entering Minimalist mode and then settings things up. So basically you are executing TrueZen commands with its default configs. 

This is what it should all look like with the recommendations I gave you above:

```lua
lua << EOF
local true_zen = require("true-zen")
true_zen.setup({
  left = {
    hidden_number = true,
    hidden_relativenumber = false,
    hidden_signcolumn = "no",

    shown_number = true,
    shown_relativenumber = false,
    shown_signcolumn = "no"
  },
  minimalist = {
    store_and_restore_settings = false,
    show_vals_to_read = {}
  }
})
EOF

" Truezen.nvim is awesome!
autocmd VimEnter * TZMinimalist
```

Recommendations:
* Read the README
* Grab the whole example config and take the time to configure it. I know there is a lot of stuff to configure, but trust me, it's worth it!
* If you want to enable the `left side marks` at startup then that's a GitGutter thing.

**Comment by kdav5758** [comment]
Just added the small clarification in the README: 5e73797bc831ab1cdade2c84b81d45d592abbffd

**Comment by qazip** [comment]
Nevermind. It is the "show_signcolumn". Changing that to true fixed it. May I ask one quick question? In the config you gave me just now, what is the point of:
```
    hidden_number = true,
    hidden_relativenumber = false,
    hidden_signcolumn = "no",

    shown_number = true,
    shown_relativenumber = false,
    shown_signcolumn = "no"
```

They seem to be opposites of each other. That is, in the first block, you have "hidden_X", and in the next block you have "shown_X". That is a bit confusing to my brain lol. First you do "hidden_number = True", and then "shown_number = True". I understand that as first hiding numbers and then showing numbers, which could be done with just one of those variables?

**Comment by kdav5758** [comment]
> In the config you gave me just now, what is the point of:

Because there are two states (`shown` or `hidden`), and I wanted the plugin to be fully customizable, that's basically the reason why the config seems too long even though the plugin does a relatively simple thing! Like for example, `ideal_writing_area_width` and `just_do_it_for_me`. Only after reading the description you'll understand that they are not the same thing and that there is a hierarchy where one rules over the other.

> ...which could be done with just one of those variables?

Not really. What if I want to have a `shown_x = true` and the `hidden_x = true` as well? That's why users have 2 vars for each setting, for the two different states.
