### ISSUE TITLE
TrueZen eats tab and split on running :TZAtaraxis

### ISSUE THREAD

**Issue by maxigaz** [kdav5758/TrueZen.nvim#26]
While I was trying out TrueZen.nvim with the default settings in Neovim v0.5.0-dev+1318-g61aefaf29, I encountered a weird bug.

To reproduce it:

1. Open file1.
2. Create a new split (either horizontal or vertical).
3. Open file2 on a new tab (`:tabe file2`).
4. Switch back to the tab with the two splits.
5. Run `:TZAtaraxis`. A message should come up that `force_when_plus_one_window` has to be set.
6. Switch to the tab with file2.
7. Run `:TZAtaraxis` again.

What happens is that Neovim shows only file1 with all the UI still displayed, and the other tab and split completely disappear. The following error appears as well:

```
E5108: Error executing lua ...Zen.nvim/lua/true-zen/services/mode-ataraxis/service.lua:331: attempt to compare number with nil
```

**Comment by kdav5758** [comment]
That's expected behavior. If you want your layout to be restored while still being able to execute Ataraxis on one of the splits, then use `:TZFocus` to focus the current split and then run `:TZAtaraxis`, and of course the opposite to go back. You'll need to have these settings enabled:

```lua
	ataraxis = {
		force_when_plus_one_window = true
	},
	focus = {
		focus_method = "experimental"
	}
```

Furthermore:

> 4. Switch back to the tab with the two splits.

In (N)vim, if you use `:(v)split %` to split current file and then `:tabe <other_file>`, this will ""remove"" the split, so in this case it doesn't make sense to say "go back to the tab with splits".

> 5. Run :TZAtaraxis. A message should come up that force_when_plus_one_window has to be set.

Even when you can't see the splits, they are still there, and well, TrueZen will prevent you from toggling Ataraxis in one of them if you don't have the `force_when_plus_one_window` enabled because that will otherwise break the operations that Ataraxis mode do to add the "padding" to the text, but if you still try to toggle Ataraxis when that option is not set then it'll quit you from the nvim session.

Oh and btw, I followed the steps you left above, and didn't encounter such issues:


https://user-images.githubusercontent.com/58336662/118369650-cb2f4b80-b569-11eb-99cc-64b4e3e59fdc.mp4

**Comment by maxigaz** [comment]
Thank you for the explanation!

**Comment by kdav5758** [comment]
You're welcome! always glad to help!
