### ISSUE TITLE
Possible inconsistencies with split windows

### ISSUE THREAD

**Issue by AckslD** [kdav5758/TrueZen.nvim#3]
Lets say I have a horizontal split and run `TZMinimalist` in the top window, to remove line numbers etc. Now I want to remove them also in the lower window so I go down there and run the command again to remove them but they remain and instead that status bar appear again.

Perhaps this is the intended behaviour but just wondering how one easily toggles "zen-mode" in two split windows easily.

**Comment by kdav5758** [comment]
Hello! when referring to an issue with the `TZMinimalist` command please refer to the UI part that isn't doing what it's supposed to, due to the fact that `TZMinimalist` is basically a "shortcut" for executing `TZLeft`, `TZTop`, `TZBottom`.

As you can see in the [source code](https://github.com/kdav5758/TrueZen.nvim/blob/main/lua/utils/cmd_settings.lua#L16-L36) that controls settings, everything is set locally to the buffer. However as you may notice not every command works this way, for instance, `set statusline=-`.

I'm still exploring vim autocommands to see which one would get a more consistent bahaviour. As of now, the best ones are `WinEnter`, that executes x command when entering a window and `BufWinEnter`, that executes x command when entering a buffer. With this, I can code it so that when `TZMinimalist` is toggled the settings are loaded *to the buffer* but when switching to another window/buffer the same settings are "inherited". This solves the inconsistency issue by having a consistent "flow".

As a TrueZen.nvim user, would you like the settings to be inherited among windows and buffers?

**Comment by AckslD** [comment]
Thanks for your reply @kdav5758 ! 

Personally I would like all buffers to be affected when doing `TZMinimalist` but to keep the windows and when doing `TZAtaraxis` that the buffer becomes "fullsize".

Thanks for the great work :)

**Comment by kdav5758** [comment]
Hey @AckslD! Hope you are enjoying the plugin. Yesterday a bunch of updates, new features and bug fixes were merge to main too, so be sure to check those out as well ;)

There are some new features you may want to check out regarding this closed issue:

**Ataraxis table**
![image](https://user-images.githubusercontent.com/58336662/116789822-6c9ca480-aa76-11eb-8519-c96cc020fd9c.png)

**Focus table**
![image](https://user-images.githubusercontent.com/58336662/116789836-85a55580-aa76-11eb-8f0c-5c1e17b4afa2.png)

**Integrations table**
![image](https://user-images.githubusercontent.com/58336662/116789841-91911780-aa76-11eb-8c5c-d39405000734.png)


Cheers!

**Comment by AckslD** [comment]
Awesome thanks for sharing @kdav5758! :)
