### ISSUE TITLE
Sign Column is deleted after toggle.

### ISSUE THREAD

**Issue by ahmedkhalf** [kdav5758/TrueZen.nvim#4]
1. `:set signcolumn=yes`
2. `:TZMinimalist`
3. `:TZMinimalist`
4. Sign column is no longer visible

**Comment by kdav5758** [comment]
This is expected behavior. The signcolumn makes part of the `Left UI` group, so if you want the signcolumn to be shown when TZMinimalist is untoggled, then use `shown_signcolumn = "yes"` under the `left = {}` table settings. This will ensure that the signcolumn is shown when TZMinimalist shows everything. You can try this config:

```
left = {
	hidden_number = false,
	hidden_relativenumber = false,
	hidden_signcolumn = "no",

	shown_number = true,
	shown_relativenumber = false,
	shown_signcolumn = "yes"
},
```

**Comment by ahmedkhalf** [comment]
Hum why can't it just read my settings before toggling and store them, I want to have some peace of mind, because now if I want to hide sign columns in my neovim config i'l have to change it in two places... :(
