### ISSUE TITLE
Move lua code to lua/true_zen

### ISSUE THREAD

**Issue by jedrzejboczar** [kdav5758/TrueZen.nvim#8]
Hi, thanks for this plugin, it looks cool. But a lot of files are directly in the `lua/` directory, which pollutes the namespace of `require` and so `require('config')` resolves to the file in this plugin https://github.com/kdav5758/TrueZen.nvim/blob/main/lua/config.lua. Could you please move all the files to `lua/true-zen/`? Then `require('true-zen')` would load `lua/true-zen/init.lua` and the only "visible" namespace would be `require('true-zen.*')`.

**Comment by kdav5758** [comment]
Hello @jedrzejboczar! thanks for the recommendation, I didn't know that `require('true-zen')` would resolve `lua/true-zen/init.lua`, that's basically the reason I made it that way! and also because it's my first plugin and I didn't know what the conventions were. Thanks for pointing this out and also thanks to @YaBoiBurner for the PR.

Yes, everything is now located at `lua/true-zen`, which means that `require()` should be unpolluted!
